### ISSUE TITLE
Visual bug with Hunger Remover

### ISSUE THREAD

**Issue by Pete3R** [SFort/MC-LessClutter#2]
![Minecraft_ 1 17 - Singleplayer 2021-07-06 15 12 03](https://user-images.githubusercontent.com/85805854/124606155-e41ef380-de6c-11eb-9f8f-ae65cc463967.png)

Setting "Removed armor hud" in the config to false fixes the issue.

This may also be caused by other mod since the setting itself doesn't work, my armor bar was still displayed.
I am not quite sure what mod is causing that though

Mods I am using: (from log file)

	- advancements-enlarger@0.2.4
	- amecs@1.3.4+mc.1.17
	- amecsapi@1.1.5+mc21w16a
	- antighost@1.17-fabric0.34.9-1.1.4
	- appleskin@mc1.17-2.0.0
	- architectury@2.1.20
	- audiooutput@0.0.4
	- autoconfig1u@3.3.1
	- autofish@0.9.3
	- axesareweapons@1.2-1.17
	- better_withered_mobs@1.6.0
	- betterbeds@1.2.0
	- betterdroppeditems@1.3.0-1.17
	- betterf3@1.1.5
	- bettermineshafts@1.17-1.0.0
	- betterstrongholds@1.17-1.0
	- betterthanmending@1.3.0
	- betterthirdperson@1.5.0
	- blue_endless_jankson@1.2.1
	- blur@2.1.0
	- cakechomps@1.4.0-1.17
	- cameraoverhaul@1.2.2-fabric-universal
	- capes@1.2.0
	- carpet@1.4.40
	- carpet-extra@1.4.40
	- cherishedworlds@2.0.0-1.17
	- chime@1.1.2
	- clear-skies@1.5.69
	- cleardespawn@1.17-fabric0.34.9-1.1.1
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.34
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- com_moandjiezana_toml_toml4j@0.7.2
	- craftpresence@1.8.2
	- crowdin-translate@1.3+1.17
	- cullleaves@2.2.0
	- customportalapi@0.0.1-beta32-1.17
	- customspawns@0.2
	- darkpaintings@3.0.6
	- disable_custom_worlds_advice@1.3
	- dynamicfps@2.0.4
	- dynamicsoundfilters@1.2.0+1.17
	- easiervillagertrading@1.17-fabric0.34.9-1.5.4
	- elytra_bounce@0.1.0+1.16.1
	- enchantmentdescriptions@3.0.10
	- enhanced_attack_indicator@1.0.2+1.17
	- fabric@0.36.0+1.17
	- fabric-api-base@0.3.0+a02b4463d5
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d03d
	- fabric-biome-api-v1@3.1.11+c345aea83d
	- fabric-blockrenderlayer-v1@1.1.5+a02b44633d
	- fabric-command-api-v1@1.1.1+a02b4463d5
	- fabric-commands-v0@0.2.2+92519afa3d
	- fabric-containers-v0@0.1.12+a02b44633d
	- fabric-content-registries-v0@0.2.2+a02b44633d
	- fabric-crash-report-info-v1@0.1.5+be9da3103d
	- fabric-dimensions-v1@2.0.10+a02b44633d
	- fabric-entity-events-v1@1.1.0+a02b44633d
	- fabric-events-interaction-v0@0.4.9+a722d8c03d
	- fabric-events-lifecycle-v0@0.2.1+92519afa3d
	- fabric-game-rule-api-v1@1.0.6+a02b44633d
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab61213d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-keybindings-v0@0.2.2+36b77c3e3d
	- fabric-language-kotlin@1.6.2+kotlin.1.5.20
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b44633d
	- fabric-mining-levels-v0@0.1.3+92519afa3d
	- fabric-models-v0@0.3.0+a02b44633d
	- fabric-networking-api-v1@1.0.11+b7ab61213d
	- fabric-networking-blockentity-v0@0.2.11+a02b44633d
	- fabric-networking-v0@0.3.2+92519afa3d
	- fabric-object-builder-api-v1@1.10.9+b7ab61213d
	- fabric-object-builders-v0@0.7.3+a02b44633d
	- fabric-particles-v1@0.2.4+a02b44633d
	- fabric-registry-sync-v0@0.7.10+e2961fee3d
	- fabric-renderer-api-v1@0.4.3+676f40fa3d
	- fabric-renderer-indigo@0.4.8+a02b44633d
	- fabric-renderer-registries-v1@3.2.0+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5
	- fabric-rendering-fluids-v1@0.1.13+a02b4463d5
	- fabric-rendering-v0@1.1.2+92519afa3d
	- fabric-rendering-v1@1.6.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab6121a0
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+a02b44633d
	- fabric-structure-api-v1@1.1.11+e36969833d
	- fabric-tag-extensions-v0@1.1.4+a02b44633d
	- fabric-textures-v0@1.0.6+a02b44633d
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabricloader@0.11.6
	- fallingleaves@1.7.2+1.17
	- fastchest@1.2+1.17
	- fastfurnace@1.17-3.0
	- fatxporbs@1.0.0
	- ferritecore@3.0.0
	- fiber@0.23.0-2
	- firstperson@${version}
	- gbfabrictools@1.3.4+1.17
	- grass_pass@1.0.0
	- harvest@1.2.12
	- horsestatsvanilla@4.1.8
	- hunger_remover@1.0.2
	- indium@1.0.0+rev.820073e
	- inspecio@1.0.3+1.17
	- inventoryhud@3.3.2
	- inventorysorter@1.7.9-1.17
	- iris@1.1.0-starline+build.369
	- itemmodelfix@1.0.2+1.17
	- jankson@3.0.1+j1.2.0
	- java@16
	- kyrptconfig@1.1.10-1.17
	- lambdabettergrass@1.2.0+1.17
	- lambdynlights@2.0.0+1.17
	- lazydfu@0.1.2
	- lessclutter@1.1.8
	- libgui@4.0.0-beta.4+1.17-rc1
	- libninepatch@1.1.0
	- libzoomer@0.2.1+1.17
	- lithium@0.7.2
	- lovely_snails@1.0.1+1.17
	- lowfire@1.17-2.0.0
	- maelstrom_library@1.2.1-1.17-pre1
	- malilib@0.10.0+dev.22
	- me_zeroeightsix_fiber@0.8.0-1
	- minecraft@1.17
	- minihud@0.19.0-dev.20210608.211830
	- mm@2.2
	- mob_proof_crystals@2.2.0
	- mobs_attempt_parkour@0.2.3-1.17-pre1
	- modern_beta@2.0.0-1.17
	- modmenu@2.0.2
	- monsters_in_the_closet@1.0.2+1.17
	- musicdr@1.2.1
	- neutral_animals@1.0.2
	- notenoughanimations@1.3.0
	- notenoughcrashes@3.3.1+1.17
	- noweakattack@1.1.2
	- offlineskins@1.17-v1-fabric
	- okzoomer@5.0.0-beta.2+1.17
	- omega-config@1.0.8
	- openloader@2.0.1
	- org_aperlambda_lambdajcommon@1.8.1
	- org_codehaus_groovy_groovy@3.0.8
	- org_codehaus_groovy_groovy-jsr223@3.0.8
	- org_jetbrains_kotlin_kotlin-reflect@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.20
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- particlerain@1.3.1
	- pettable@1.2.0
	- pling@1.3.0
	- preciseblockplacing@1.7
	- quickshulker@1.1.14-1.17
	- repurposed_structures@2.0.3+1.17.0
	- resolutioncontrol@3.0.0
	- satin@1.6.0-nightly.1.17-pre3
	- screenshotclipboard@1.0.6
	- seamless_loading_screen@1.3.5+1.17
	- seasons@1.2.2-BETA+1.17
	- shulkerboxtooltip@3.0.0+1.17
	- shulkerutils@1.0.1-1.17
	- slight-gui-modifications@2.0.0
	- smoothboot@1.16.5-1.6.0
	- sodium@0.3.0+IRIS1-build.73
	- spruceui@3.2.0+1.17
	- starlight@fabric-1.0.0-RC2-3a77ed1
	- suitablystackablestew@1.1.2
	- taxfreelevels@1.2
	- terra@5.4.1-BETA+b85880fc
	- terrarianslimes@1.1-BETA+1.17
	- tooltipfix@1.0.3-1.16
	- transliterationlib@1.1.0
	- trees-do-not-float@2.1.143
	- tweed@3.0.0-beta.22
	- wandering_collector@1.0.2+mc1.17
	- yungsapi@1.17-Fabric-11
	- zetamod@1.0.9

**Comment by SFort** [comment]
assuming fixed by [1.1.9](https://github.com/SFort/MC-LessClutter/releases/tag/r1.1.9)  
(at least it is my side although i didn't have all those mods installed)
